/* GENERATED by scripts/extract-kernels.mjs — DO NOT EDIT.
   The transitive closure of the physics the computational kernels name, sliced verbatim
   out of the single module block of index.html and emitted in original source order.
   Editing this file instead of index.html would create the second copy the extractor
   exists to prevent; scripts/ci.mjs regenerates it and the build fails if it differs.

   declarations: 129   ·   exported names: 131
   extracted physics, sha256 a0baea8a6b47bd691ac069e1c7e118153788d014c3c0e57aaf6ddac125ed56a4 */

const S3 = {
  R:          548.324513026856,     // Gly — curvature radius of S³
  Dcausal:    1722.612261908368,    // Gly — intrinsic causal diameter πR
  Circ:       3445.224523816736,    // Gly — full great circle 2πR
  V:          3.254188648717e9,     // Gly³ — proper volume 2π²R³
  tCoh:       1722.612261908368,    // Gyr — full causal accessibility time πR/c
  t0:         13.787718785602,      // Gyr — age of the hot history
  theta0deg:  1.440712710740,       // ° — ct0 arc on a great circle
  Dparticle:  46.125169765204,      // Gly — particle horizon (background-dependent input)
  thetaPdeg:  4.819732647519,       // ° — particle-horizon arc
  chiP:       0.08412,              // rad — D_particle / R
  GammaObs:   1.2613777438877e-4,   // volume fraction of the observable domain
};

const PHI = (1+Math.sqrt(5))/2;

const LN_PHI = Math.log(PHI), LOG10_PHI = Math.log10(PHI);

const LY_M = 9.4607304725808e15, GLY_M = LY_M*1e9;

const FBS = {
  lP: 1.616255e-35,                 // m — Planck length (seed radius, N = 0)
  tP: 5.391247e-44,                 // s — Planck time
  Nrec: 266,                        // published level label; not derived from the CoScale clock
  Nmax: 312,
};

FBS.Ns3 = Math.log(S3.R*GLY_M/FBS.lP)/LN_PHI;

FBS.Nobs = Math.log(S3.Dparticle*GLY_M/FBS.lP)/LN_PHI;

const levelR   = N => FBS.lP*Math.exp(N*LN_PHI);

const ZPF={
  HBAR:1.054571817e-34, C:2.99792458e8, G:6.67430e-11, KB:1.380649e-23,
  ZETA_M3:1/120, SCALAR_COEFF:1/240,
};

ZPF.EP=ZPF.HBAR*ZPF.C/FBS.lP;

ZPF.TP=ZPF.HBAR*ZPF.C/(ZPF.KB*FBS.lP);

const zpOmega=(N,beta=1)=>beta*ZPF.C/levelR(N);

const zpModeEnergy=(N,beta=1)=>0.5*ZPF.HBAR*zpOmega(N,beta);

const zpShellEnergy=(N,beta=1)=>zpModeEnergy(N,beta)*beta*beta;

const zpBareEnergy=(N,M=1)=>ZPF.HBAR*ZPF.C/(8*levelR(N))*M*M*(M+1)*(M+1);

const zpCasimirEnergy=N=>ZPF.SCALAR_COEFF*ZPF.HBAR*ZPF.C/levelR(N);

const zpCasimirDensity=N=>zpCasimirEnergy(N)/(2*Math.PI*Math.PI*Math.pow(levelR(N),3));

const zpModeTemperature=(N,beta=1)=>ZPF.HBAR*zpOmega(N,beta)/ZPF.KB;

const zpEqualTemperature=(N,beta=1)=>zpModeTemperature(N,beta)/Math.log(3);

const zpCompactness=N=>Math.pow(FBS.lP/levelR(N),2);

const zpCasimirCompactness=N=>zpCompactness(N)/120;

const zpActionInvariant=(N,beta=1)=>zpModeEnergy(N,beta)*levelR(N)/ZPF.C;

const zpCasimirAction=N=>zpCasimirEnergy(N)*levelR(N)/ZPF.C;

function zpBose(x){ return x>700?0:1/Math.expm1(Math.max(x,1e-12)); }

function zpMeanModeEnergy(N,beta=1,theta=1/Math.log(3)){
  // theta = k_B T R/(ħc); Planck mean = ½ħω + ħω/(exp(β/theta)-1)
  const e0=zpModeEnergy(N,beta); return e0*(1+2*zpBose(beta/Math.max(theta,1e-12)));
}

const ZP_TH_BUDGET=400000;

const zpThermalTermsNeeded=theta=>Math.ceil(Math.max(theta,1e-12)*39.2)+64;

function zpThermalScalarFactor(theta,M){
  theta=Math.max(theta,1e-12);
  const cap=M!=null?M:Math.min(ZP_TH_BUDGET,zpThermalTermsNeeded(theta));
  let sum=0;
  for(let b=1;b<=cap;b++){ const x=b/theta; if(x>745) break;
    const term=b*b*b*zpBose(x); sum+=term;
    /* only allowed to stop AFTER the peak at β≈3θ has been passed */
    if(b>4*theta+32 && term<1e-17*sum) break; }
  return sum;
}

function zpHopfCharges(beta){
  beta=Math.max(1,Math.round(beta)); const q=[];
  for(let m=-(beta-1);m<=beta-1;m+=2)q.push(m);
  return q; // β U(1)-fibre charges, multiplicity β each; β·β=β² total degeneracy
}

function zpRung(N,beta=1,M=24,theta=1/Math.log(3)){
  const R=levelR(N), e0=zpModeEnergy(N,beta), shell=zpShellEnergy(N,beta), ec=zpCasimirEnergy(N);
  return {N,R,beta,omega:zpOmega(N,beta),nu:zpOmega(N,beta)/(2*Math.PI),e0,shell,
    bare:zpBareEnergy(N,M),casimir:ec,rho:zpCasimirDensity(N),pressure:zpCasimirDensity(N)/3,
    Tmode:zpModeTemperature(N,beta),Teq:zpEqualTemperature(N,beta),mean:zpMeanModeEnergy(N,beta,theta),
    thermalScalar:(ZPF.HBAR*ZPF.C/R)*zpThermalScalarFactor(theta),compact:zpCompactness(N),
    compactCasimir:zpCasimirCompactness(N),action:zpActionInvariant(N,beta),casimirAction:zpCasimirAction(N),
    charges:zpHopfCharges(beta),M,theta};
}

const zpTemperatureOf=(N,theta)=>theta*ZPF.HBAR*ZPF.C/(ZPF.KB*levelR(N));

const BIX_C=Math.PI;

const bixBetas=(bp,bm)=>[bp+Math.sqrt(3)*bm, bp-Math.sqrt(3)*bm, -2*bp];

function bixV(bp,bm){ const [b1,b2,b3]=bixBetas(bp,bm);
  return 0.5*(Math.exp(4*b1)+Math.exp(4*b2)+Math.exp(4*b3)
             -2*Math.exp(-2*b1)-2*Math.exp(-2*b2)-2*Math.exp(-2*b3)); }

const bixJAC=[[1,Math.sqrt(3)],[1,-Math.sqrt(3)],[-2,0]];

function bixDV(bp,bm){                       /* exact: dV/dβ_i = 2(e^{4β_i}+e^{−2β_i}) */
  const b=bixBetas(bp,bm), g=b.map(x=>2*(Math.exp(4*x)+Math.exp(-2*x)));
  return [g[0]*bixJAC[0][0]+g[1]*bixJAC[1][0]+g[2]*bixJAC[2][0],
          g[0]*bixJAC[0][1]+g[1]*bixJAC[1][1]+g[2]*bixJAC[2][1]]; }

const BIX_C2=BIX_C*BIX_C;

const bixLapse=a=>12*BIX_C*Math.exp(3*a);

const bixHtau=(y,L)=>0.5*(-y[3]*y[3]+y[4]*y[4]+y[5]*y[5])
  +12*BIX_C2*Math.exp(4*y[0])*bixV(y[1],y[2])+24*BIX_C2*L*Math.exp(6*y[0]);

function bixFlow(z,L){
  const e4=Math.exp(4*z[0]), g=bixDV(z[1],z[2]);
  return [-z[3], z[4], z[5],
    -(48*BIX_C2*e4*bixV(z[1],z[2])+144*BIX_C2*L*Math.exp(6*z[0])),
    -12*BIX_C2*e4*g[0], -12*BIX_C2*e4*g[1], bixLapse(z[0])]; }

function bixSeed(a,bp,bm,pp,pm,L,branch){
  const base=24*BIX_C2*Math.exp(4*a)*bixV(bp,bm)+48*BIX_C2*L*Math.exp(6*a);
  let s=1, disc=pp*pp+pm*pm+base;
  if(disc<0){ if(!pp&&!pm) return null;
    s=Math.sqrt((-base)*1.05/(pp*pp+pm*pm)); pp*=s; pm*=s; disc=pp*pp+pm*pm+base; }
  if(disc<0) return null;
  return {y:[a,bp,bm,(branch==='expanding'?-1:1)*Math.sqrt(disc),pp,pm],scale:s}; }

const BIX_A=[[],[0.2],[3/40,9/40],[44/45,-56/15,32/9],[19372/6561,-25360/2187,64448/6561,-212/729],
  [9017/3168,-355/33,46732/5247,49/176,-5103/18656],[35/384,0,500/1113,125/192,-2187/6784,11/84]];

const BIX_B=[35/384,0,500/1113,125/192,-2187/6784,11/84,0];

const BIX_B2=[5179/57600,0,7571/16695,393/640,-92097/339200,187/2100,1/40];

function bixStep(z,L,h,mask){
  const k=[], n=z.length, F=n>7?bixExtFlow:bixFlow, m=mask??n;
  for(let i=0;i<7;i++){ const zi=z.slice();
    for(let j=0;j<i;j++){ const c=BIX_A[i][j]; if(!c) continue;
      for(let d=0;d<n;d++) zi[d]+=h*c*k[j][d]; }
    k.push(F(zi,L)); }
  const y5=z.slice(); let err=0;
  for(let d=0;d<n;d++){ let a=0,b=0;
    for(let i=0;i<7;i++){ a+=BIX_B[i]*k[i][d]; b+=BIX_B2[i]*k[i][d]; }
    y5[d]+=h*a;
    if(d<m) err=Math.max(err,Math.abs(h*(a-b))/(1+Math.abs(y5[d]))); }
  return {y:y5,err}; }

const bixShear=y=>(y[4]*y[4]+y[5]*y[5])/Math.max(1e-300,y[3]*y[3]);

function bixIntegrate(ic,L,opt={}){
  if(!ic) return null;
  const tauMax=opt.tauMax??5, tol=opt.tol??1e-11, drop=opt.drop??9, rise=opt.rise??6, N=opt.samples??420;
  let z=[...ic.y,0], tau=0, h=1e-5, steps=0, resid=0, bounces=0, prevRad=null, prevUp=null, stop='window';
  const a0=z[0], scaleOf=y=>Math.abs(12*BIX_C2*Math.exp(4*y[0])*bixV(y[1],y[2]))
    +24*BIX_C2*Math.abs(L)*Math.exp(6*y[0])+0.5*(y[3]*y[3]+y[4]*y[4]+y[5]*y[5])+1;
  /* sample by STEP with decimation, not on a fixed τ grid.  A grid keyed to the
     requested window collapses to a handful of points whenever the orbit leaves early —
     a de Sitter escape can be over in τ = 0.04 out of a 2.5 window — and the charts
     then have nothing to draw.  Decimating keeps the resolution wherever the orbit
     actually lives, and the last point is always kept. */
  const tr=[]; let stride=1, sinceKeep=0;
  const push=()=>tr.push({tau,t:z[6],a:z[0],bp:z[1],bm:z[2],pa:z[3],pp:z[4],pm:z[5],sh:bixShear(z)});
  push();
  let aMin=z[0], aMax=z[0], shMax=bixShear(z), bMax=Math.hypot(z[1],z[2]);
  const budget=opt.maxSteps??60000;
  while(tau<tauMax&&steps<budget){
    if(tau+h>tauMax) h=tauMax-tau;
    const st=bixStep(z,L,h);
    if(st.err>tol&&h>1e-13){ h*=Math.max(0.2,0.9*Math.pow(tol/st.err,0.2)); continue; }
    z=st.y; tau+=h; steps++;
    h*=Math.min(5,Math.max(0.2,0.9*Math.pow(tol/Math.max(st.err,1e-16),0.2)));
    resid=Math.max(resid,Math.abs(bixHtau(z,L))/scaleOf(z));
    aMin=Math.min(aMin,z[0]); aMax=Math.max(aMax,z[0]);
    shMax=Math.max(shMax,bixShear(z)); bMax=Math.max(bMax,Math.hypot(z[1],z[2]));
    const rad=Math.hypot(z[1],z[2]), up=prevRad===null?null:(rad>prevRad);
    if(up!==null&&prevUp!==null&&up!==prevUp) bounces++;
    if(up!==null) prevUp=up; prevRad=rad;
    if(++sinceKeep>=stride){ sinceKeep=0; push();
      if(tr.length>N){ for(let i=1,j=1;i<tr.length;i+=2,j++) tr[j]=tr[i];
        tr.length=Math.ceil(tr.length/2); stride*=2; } }
    if(z[0]<a0-drop){ stop='collapse'; break; }
    if(z[0]>a0+rise){ stop='de Sitter escape'; break; }
    if(!Number.isFinite(z[0]+z[3]+z[6])){ stop='overflow'; break; }
  }
  if(tr.length&&tr[tr.length-1].tau!==tau) push();      /* the endpoint is never dropped */
  if(steps>=budget&&stop==='window') stop='step budget';
  return {y:z.slice(0,6),tau,t:z[6],resid,stop,a0,aMin,aMax,shMax,shEnd:bixShear(z),bMax,
          bounces,trace:tr,steps,bounded:stop==='window',scale:ic.scale,L}; }

function bixD2V(bp,bm){                      /* Hess V = Jᵀ diag(∂²V/∂β_i²) J */
  const b=bixBetas(bp,bm), h=b.map(x=>8*Math.exp(4*x)-4*Math.exp(-2*x));
  const M=[[0,0],[0,0]];
  for(let i=0;i<3;i++)for(let r=0;r<2;r++)for(let c=0;c<2;c++) M[r][c]+=h[i]*bixJAC[i][r]*bixJAC[i][c];
  return M; }

function bixJacobian(y,L){                   /* exact Jacobian of bixFlow, for the tangent */
  const e4=Math.exp(4*y[0]), e6=Math.exp(6*y[0]), g=bixDV(y[1],y[2]), H=bixD2V(y[1],y[2]);
  const M=Array.from({length:6},()=>new Array(6).fill(0));
  M[0][3]=-1; M[1][4]=1; M[2][5]=1;
  M[3][0]=-(192*BIX_C2*e4*bixV(y[1],y[2])+864*BIX_C2*L*e6);
  M[3][1]=-48*BIX_C2*e4*g[0]; M[3][2]=-48*BIX_C2*e4*g[1];
  M[4][0]=-48*BIX_C2*e4*g[0]; M[4][1]=-12*BIX_C2*e4*H[0][0]; M[4][2]=-12*BIX_C2*e4*H[0][1];
  M[5][0]=-48*BIX_C2*e4*g[1]; M[5][1]=-12*BIX_C2*e4*H[1][0]; M[5][2]=-12*BIX_C2*e4*H[1][1];
  return M; }

function bixExtFlow(z,L){
  const d=bixFlow(z.slice(0,7),L);
  if(z.length>7){ const M=bixJacobian(z,L);
    for(let i=0;i<6;i++){ let sm=0; for(let j=0;j<6;j++) sm+=M[i][j]*z[7+j]; d[7+i]=sm; } }
  return d; }

const BIX_LY_W0=1e-8;

const BIX_LY_CUT=0.85;

function bixLyapExp(ic,L,opt={}){
  if(!ic) return null;
  const tauMax=opt.tauMax??5, tol=opt.tol??1e-11, drop=opt.drop??9, rise=opt.rise??6;
  let z=[...ic.y,0,0,BIX_LY_W0,0,0,0,0], tau=0, h=1e-5, steps=0, lySum=0, stop='window';
  const a0=z[0], maxSteps=opt.maxSteps??120000;
  while(tau<tauMax&&steps<maxSteps){
    if(tau+h>tauMax) h=tauMax-tau;
    /* the tangent must not drive the step size, so the error mask stops at the physical
       seven components — a renormalised tangent would otherwise force h to zero */
    const st=bixStep(z,L,h,7);
    if(st.err>tol&&h>1e-13){ h*=Math.max(0.2,0.9*Math.pow(tol/st.err,0.2)); continue; }
    z=st.y; tau+=h; steps++;
    h*=Math.min(5,Math.max(0.2,0.9*Math.pow(tol/Math.max(st.err,1e-16),0.2)));
    const nw=Math.hypot(...z.slice(7));
    if(nw>1e-4||nw<1e-12){ lySum+=Math.log(nw/BIX_LY_W0);
      const sc=BIX_LY_W0/nw; for(let i=0;i<6;i++) z[7+i]*=sc; }
    if(z[0]<a0-drop){ stop='collapse'; break; }
    if(z[0]>a0+rise){ stop='de Sitter escape'; break; }
    if(!Number.isFinite(z[0]+z[3]+z[4])){ stop='overflow'; break; }
  }
  if(steps>=maxSteps) stop='step budget';
  lySum+=Math.log(Math.hypot(...z.slice(7))/BIX_LY_W0);
  return {lam:tau>0?lySum/tau:null, tau, stop, steps, bounded:stop==='window'};
}

function bixLyapunov(ic,L,opt={}){
  const T=opt.tauMax??5;
  const a=bixLyapExp(ic,L,{...opt,tauMax:T});
  /* an unbounded run returns NO number.  Returning a.lam here alongside the words "not
     measured" is precisely the contradiction this whole function exists to avoid, and it
     is what the first version did. */
  if(!a||!a.bounded)
    return {lambda:null, ratio:null, bounded:false,
      verdict:'not measured — the run is not bounded, and on an escape the tangent grows with the inflating background rather than with any sensitivity'};
  if(a.lam===null||!(a.lam>0))
    return {lambda:a.lam, ratio:null, bounded:true,
      verdict:'regular — the tangent did not grow over the window'};
  const b=bixLyapExp(ic,L,{...opt,tauMax:2*T});
  if(!b||!b.bounded||b.lam===null)
    return {lambda:a.lam, ratio:null, bounded:true,
      verdict:'not decided — the doubled window is not bounded, so the two estimates are not comparable'};
  const ratio=b.lam/a.lam;
  return {lambda:b.lam, ratio, bounded:true,
    /* the asymptotic null hypothesis is only a null hypothesis for large windows: at
       T = 2 it evaluates to exactly 1, which would read as "regular means chaotic". */
    expectedIfRegular:T>=4?0.5+Math.LN2/(2*Math.log(T)):null,
    verdict:ratio>BIX_LY_CUT?'plateau — sensitive dependence':'decaying — regular'};
}

function bixClassify(r,ly){
  if(!r) return 'unreachable';
  if(Math.hypot(...bixFlow([...r.y,0],r.L).slice(0,6))<1e-10&&Math.hypot(r.y[1],r.y[2])<1e-10) return 'stationary';
  if(r.stop==='collapse'||r.stop==='overflow') return 'singular';
  if(r.stop==='de Sitter escape') return 'transient';
  if(r.stop==='step budget') return 'transient';
  const q=r.trace.map(s=>[s.bp,s.bm,s.pp,s.pm]), n=q.length;
  const sc=Math.max(1e-12,Math.max(...q.map(v=>Math.hypot(...v))));
  let rec=Infinity;
  for(let i=Math.floor(n*0.2);i<n;i++) rec=Math.min(rec,Math.hypot(...q[i].map((v,k)=>v-q[0][k]))/sc);
  if(rec<0.02) return 'periodic';
  /* and the sixth class, which the recurrence test alone can never see: bounded WITH
     sensitive dependence.  Supplied only when a Lyapunov measurement is handed in, so a
     caller that does not pay for one gets exactly the five classes it paid for rather
     than a guess dressed as a sixth. */
  if(ly&&ly.bounded&&ly.ratio!==null&&ly.ratio>BIX_LY_CUT) return 'chaotic';
  return r.bounces>=3?'quasiperiodic':'transient'; }

function fibSMatrix(){
  const d=Math.sqrt(1+PHI_R*PHI_R);
  return [[{re:1/d,im:0},{re:PHI_R/d,im:0}],[{re:PHI_R/d,im:0},{re:-1/d,im:0}]]; }

const FIB_N3=(a,b,c)=>((a+b+c)===1?0:1);

let FIB_FR=null;

function fibFR(){ if(!FIB_FR){ const i=1/PHI_R, s=1/Math.sqrt(PHI_R); FIB_FR=[[i,s],[s,-i]]; } return FIB_FR; }

function fibFsym(a,b,c,d,e,f){
  if(!FIB_N3(a,b,e)||!FIB_N3(e,c,d)||!FIB_N3(b,c,f)||!FIB_N3(a,f,d)) return 0;
  if(a===1&&b===1&&c===1&&d===1) return fibFR()[e][f];
  return 1;                                     /* any trivial label ⇒ the move is the identity */
}

function fibPentagon(){
  let worst=0,n=0;
  for(let a=0;a<2;a++)for(let b=0;b<2;b++)for(let c=0;c<2;c++)for(let d=0;d<2;d++)
  for(let e=0;e<2;e++)for(let f=0;f<2;f++)for(let g=0;g<2;g++)for(let k=0;k<2;k++)for(let l=0;l<2;l++){
    const L=fibFsym(f,c,d,e,g,l)*fibFsym(a,b,l,e,f,k);
    let R=0; for(let h=0;h<2;h++) R+=fibFsym(a,b,c,g,f,h)*fibFsym(a,h,d,e,g,k)*fibFsym(b,c,d,k,h,l);
    n++; worst=Math.max(worst,Math.abs(L-R));
  }
  return {worst,cases:n};
}

function fibHexagon(th1,thT){
  const R=(a,b,c)=>{ if(FIB_N3(a,b,c)===0) return [0,0];
    if(a===0||b===0) return [1,0];
    const t=(c===0)?th1:thT; return [Math.cos(t),Math.sin(t)]; };
  const cx=(x,y)=>[x[0]*y[0]-x[1]*y[1], x[0]*y[1]+x[1]*y[0]];
  let worst=0;
  for(let a=0;a<2;a++)for(let b=0;b<2;b++)for(let c=0;c<2;c++)for(let d=0;d<2;d++)
  for(let g=0;g<2;g++)for(let f=0;f<2;f++){
    let L=cx(R(c,a,g),[fibFsym(a,c,b,d,g,f),0]); L=cx(L,R(c,b,f));
    let Rt=[0,0];
    for(let e=0;e<2;e++){ let t=[fibFsym(c,a,b,d,g,e),0]; t=cx(t,R(c,e,d));
      t=cx(t,[fibFsym(a,b,c,d,e,f),0]); Rt=[Rt[0]+t[0],Rt[1]+t[1]]; }
    worst=Math.max(worst,Math.hypot(L[0]-Rt[0],L[1]-Rt[1]));
  }
  return worst;
}

let fibAxiomCache=null;

function fibAxioms(){
  if(fibAxiomCache) return fibAxiomCache;
  const P=fibPentagon();
  fibAxiomCache={pentagon:P.worst, cases:P.cases,
    hexRight:fibHexagon(4*Math.PI/5,-3*Math.PI/5),
    hexMirror:fibHexagon(-4*Math.PI/5,3*Math.PI/5),
    hexMixed:fibHexagon(4*Math.PI/5,3*Math.PI/5)};
  return fibAxiomCache;
}

function fibMonodromy(a,b){
  const S=fibSMatrix();
  return (S[a][b].re*S[0][0].re)/(S[a][0].re*S[0][b].re);
}

const CAP_Q_STAR = 3.307251460713979e122;

const CAP_NU     = 0.5;

const CAP_BG2    = 0.559754586;

const CAP_XI     = 0.99916928;

const CAP_N_PHI  = 292;

const CAP_LP     = 1.616255e-35;

const CAP_U_STAR = Math.log(CAP_Q_STAR);

const CAP_PHI    = (1+Math.sqrt(5))/2;

const CAP_OMEGA_L=0.6889, CAP_D_OMEGA=0.0056, CAP_H0=67.66, CAP_D_H0=0.42;

const CAP_LAM_OBS=(()=>{ const H=CAP_H0*1e3/3.0856775814913673e22, c=299792458;
  return 3*CAP_OMEGA_L*H*H/(c*c); })();

const CAP_LAM_SIG=CAP_LAM_OBS*Math.hypot(CAP_D_OMEGA/CAP_OMEGA_L,2*CAP_D_H0/CAP_H0);

const capGamma  = d=>Math.exp(d)*(d-1)+1;

const capGammaD = d=>Math.exp(d)*d;

const capLambda = u=>3*Math.PI/(CAP_LP*CAP_LP*Math.exp(u));

const capNphi   = u=>(u-Math.log(Math.PI))/(2*Math.log(CAP_PHI));

const capBg2    = u=>16*Math.PI*Math.PI/(u-Math.log(CAP_XI));

const capSigma  = u=>(capLambda(u)-CAP_LAM_OBS)/CAP_LAM_SIG;

const CAP_GATES=[
  {key:'A', tag:'HBAH',
   name:['recursion gate','ворота рекурсии','Rekursionstor'],
   full:['Hopf–Bradlow–APS–HC recursion','рекурсия Хопфа–Брэдлоу–APS–HC','Hopf–Bradlow–APS–HC-Rekursion'],
   supplies:'N_φ = '+CAP_N_PHI, brief:'N_φ = '+CAP_N_PHI,
   u:()=>Math.log(Math.PI)+2*CAP_N_PHI*Math.log(CAP_PHI),
   spread:()=>2*Math.log(CAP_PHI),
   role:['locator','локатор','Lokator']},
  {key:'B', tag:'GLSM',
   name:['scheme gate','ворота схемы','Schemator'],
   full:['GLSM / stringy edge matching','GLSM / струнное согласование края','GLSM/String-Randabgleich'],
   supplies:'b g_∂² = '+CAP_BG2+', Ξ = '+CAP_XI, brief:'b g², Ξ',
   u:()=>Math.log(CAP_XI)+16*Math.PI*Math.PI/CAP_BG2,
   spread:()=>16*Math.PI*Math.PI*5e-10/(CAP_BG2*CAP_BG2),   /* last quoted digit of b g² */
   role:['predictor','предсказатель','Prädiktor']},
  {key:'C', tag:'DET',
   name:['determinant line','детерминантная линия','Determinantenlinie'],
   full:['determinant-line / heat-kernel coefficient','детерминантная линия / коэффициент теплового ядра','Determinantenlinie / Wärmekern'],
   supplies:'ν = 1/2', brief:'ν = ½',
   u:()=>CAP_U_STAR+CAP_NU/CAP_Q_STAR,
   /* u★ + ν/q★ rounds to u★ exactly at double precision — 282 has ~1e-14 of resolution
      and the shift is 1e-123 — so the displacement is stated directly rather than
      recovered by a subtraction that is guaranteed to return zero. */
   dU:()=>CAP_NU/CAP_Q_STAR,
   spread:()=>CAP_NU/CAP_Q_STAR,
   role:['structural','структурный','strukturell']},
];

function capGateBudget(){
  return CAP_GATES.map(g=>{
    const u=g.u(), sp=g.spread();
    return {key:g.key, tag:g.tag, u, spread:sp,
      lambda:capLambda(u), sigma:capSigma(u),
      /* the gate's own width, converted EXACTLY rather than linearised: Λ ∝ e^{−u} is
         convex, so |dΛ/Λ| = |du| overstates a width as wide as a golden rung. */
      sigmaWidth:Math.abs(capSigma(u-sp/2)-capSigma(u+sp/2))/2,
      dU:g.dU?g.dU():u-CAP_U_STAR};
  });
}

const specC=(al,bp,bm)=>bixBetas(bp,bm).map(b=>Math.exp(-2*al-2*b));

function specBlock(j,c){
  const n=Math.round(2*j)+1, M=Array.from({length:n},()=>new Array(n).fill(0));
  const [c1,c2,c3]=c, sm=(c1+c2)/2, d=(c1-c2)/4, m=k=>-j+k;
  for(let k=0;k<n;k++){ const mm=m(k); M[k][k]=0.5*(sm*(j*(j+1)-mm*mm)+c3*mm*mm); }
  for(let k=0;k+2<n;k++){ const mm=m(k);
    const v=0.5*d*Math.sqrt((j-mm)*(j+mm+1))*Math.sqrt((j-mm-1)*(j+mm+2));
    M[k][k+2]+=v; M[k+2][k]+=v; }
  return M;
}

function specEig(Ain){
  const n=Ain.length, A=Ain.map(r=>r.slice());
  for(let sweep=0;sweep<100;sweep++){
    let off=0; for(let p=0;p<n;p++)for(let q=p+1;q<n;q++) off+=A[p][q]*A[p][q];
    if(off<1e-30) break;
    for(let p=0;p<n;p++)for(let q=p+1;q<n;q++){
      if(Math.abs(A[p][q])<1e-300) continue;
      const th=(A[q][q]-A[p][p])/(2*A[p][q]);
      const t=Math.sign(th||1)/(Math.abs(th)+Math.sqrt(th*th+1));
      const co=1/Math.sqrt(t*t+1), si=t*co;
      for(let k=0;k<n;k++){ const akp=A[k][p], akq=A[k][q];
        A[k][p]=co*akp-si*akq; A[k][q]=si*akp+co*akq; }
      for(let k=0;k<n;k++){ const apk=A[p][k], aqk=A[q][k];
        A[p][k]=co*apk-si*aqk; A[q][k]=si*apk+co*aqk; }
    }
  }
  return A.map((r,i)=>r[i]).sort((a,b)=>a-b);
}

function specSpectrum(al,bp,bm,jMax){
  const c=specC(al,bp,bm), blocks=[];
  for(let t=1;t<=Math.round(2*jMax);t++){ const j=t/2;
    const ev=specEig(specBlock(j,c));
    blocks.push({j, ev, blockDim:ev.length, spectator:Math.round(2*j)+1,
      total:(Math.round(2*j)+1)*(Math.round(2*j)+1)}); }
  const all=blocks.flatMap(b=>b.ev.map(e=>({e, j:b.j, mult:b.spectator})));
  all.sort((x,y)=>x.e-y.e);
  const distinct=[];
  for(const x of all){
    const last=distinct[distinct.length-1];
    if(last&&Math.abs(x.e-last.value)<=1e-9*Math.max(1,Math.abs(x.e))) last.multiplicity+=x.mult;
    else distinct.push({value:x.e, multiplicity:x.mult, j:x.j});
  }
  return {c, blocks, distinct,
    lowest:distinct.length?distinct[0].value:null,
    gap:distinct.length>1?distinct[1].value-distinct[0].value:null,
    /* the trace identity, recomputed live rather than quoted, so a broken build says so */
    traceResidual:(()=>{ let w=0;
      for(const b of blocks){ const tr=b.ev.reduce((a,x)=>a+x,0);
        const want=0.5*(c[0]+c[1]+c[2])*b.j*(b.j+1)*(2*b.j+1)/3;
        w=Math.max(w,Math.abs(tr-want)/Math.abs(want)); } return w; })()};
}

const pcMuBlock=(j,bp,bm)=>{
  const c=bixBetas(bp,bm).map(b=>Math.exp(-2*b));
  const n=Math.round(2*j)+1, M=Array.from({length:n},()=>new Array(n).fill(0));
  const [c1,c2,c3]=c, sm=(c1+c2)/2, d=(c1-c2)/4, m=k=>-j+k;
  for(let k=0;k<n;k++){ const mm=m(k); M[k][k]=0.5*(sm*(j*(j+1)-mm*mm)+c3*mm*mm); }
  for(let k=0;k+2<n;k++){ const mm=m(k);
    const v=0.5*d*Math.sqrt((j-mm)*(j+mm+1))*Math.sqrt((j-mm-1)*(j+mm+2));
    M[k][k+2]+=v; M[k+2][k]+=v; }
  return M; };

const pcMu=(j,idx,bp,bm)=>specEig(pcMuBlock(j,bp,bm))[idx];

const PC_H=1e-5;

function pcExtFlow(z,L,j,idx){
  const d=bixFlow(z.slice(0,7),L);
  const mu=pcMu(j,idx,z[1],z[2]), Om=Math.sqrt(Math.max(mu,1e-300));
  const dp=(pcMu(j,idx,z[1]+PC_H,z[2])-pcMu(j,idx,z[1]-PC_H,z[2]))/(2*PC_H);
  const dm=(pcMu(j,idx,z[1],z[2]+PC_H)-pcMu(j,idx,z[1],z[2]-PC_H))/(2*PC_H);
  const g=((dp*z[4]+dm*z[5])/(2*Om))/(2*Om);
  const [ar,ai,br,bi,th]=z.slice(7);
  const c2=Math.cos(2*th), s2=Math.sin(2*th);
  d[7]=g*( br*c2 - bi*s2);  d[8] =g*( br*s2 + bi*c2);
  d[9]=g*( ar*c2 + ai*s2);  d[10]=g*(-ar*s2 + ai*c2);
  d[11]=Om;
  return d; }

function pcCreate(ic,L,opt={}){
  if(!ic) return null;
  const j=opt.j??1, idx=opt.idx??0, tauMax=opt.tauMax??1, tol=opt.tol??1e-11;
  const drop=opt.drop??9, rise=opt.rise??6, maxSteps=opt.maxSteps??200000;
  let z=[...ic.y,0, 1,0, 0,0, 0], tau=0, h=1e-6, steps=0, stop='window';
  const a0=z[0]; let wr=0, muMin=Infinity, muMax=-Infinity;
  /* the tangent-free error mask: the Bogoliubov block is bounded by construction and
     must not be allowed to drive the step size */
  while(tau<tauMax&&steps<maxSteps){
    if(tau+h>tauMax) h=tauMax-tau;
    const k=[], n=z.length;
    for(let i=0;i<7;i++){ const zi=z.slice();
      for(let q=0;q<i;q++){ const c=BIX_A[i][q]; if(!c) continue;
        for(let m=0;m<n;m++) zi[m]+=h*c*k[q][m]; }
      k.push(pcExtFlow(zi,L,j,idx)); }
    const y=z.slice(); let err=0;
    for(let m=0;m<n;m++){ let s5=0,s4=0;
      for(let i=0;i<7;i++){ s5+=BIX_B[i]*k[i][m]; s4+=BIX_B2[i]*k[i][m]; }
      y[m]=z[m]+h*s5; err=Math.max(err,Math.abs(h*(s5-s4))/(1+Math.abs(y[m]))); }
    if(err>tol&&h>1e-14){ h*=Math.max(0.2,0.9*Math.pow(tol/err,0.2)); continue; }
    z=y; tau+=h; steps++;
    h*=Math.min(5,Math.max(0.2,0.9*Math.pow(tol/Math.max(err,1e-16),0.2)));
    wr=Math.max(wr,Math.abs((z[7]*z[7]+z[8]*z[8])-(z[9]*z[9]+z[10]*z[10])-1));
    const mu=pcMu(j,idx,z[1],z[2]); muMin=Math.min(muMin,mu); muMax=Math.max(muMax,mu);
    if(z[0]<a0-drop){ stop='collapse'; break; }
    if(z[0]>a0+rise){ stop='de Sitter escape'; break; }
    if(!Number.isFinite(z[0]+z[7]+z[9])){ stop='overflow'; break; }
  }
  if(steps>=maxSteps&&stop==='window') stop='step budget';
  return {n:z[9]*z[9]+z[10]*z[10], wronskian:wr, tau, stop, steps,
    muSwing:muMax-muMin, muMin, muMax, alphaGrowth:z[0]-a0}; }

function ebkAction(E,L,c,N){
  const [c1,c2,c3]=c; N=N||8000; let s=0, allPos=true;
  for(let i=0;i<N;i++){ const ph=2*Math.PI*(i+0.5)/N;
    const gg=c1*Math.cos(ph)*Math.cos(ph)+c2*Math.sin(ph)*Math.sin(ph), den=c3-gg;
    const v=Math.abs(den)<1e-300?0:(2*E-L*L*gg)/den;
    if(v<=0) allPos=false; else s+=Math.sqrt(v); }
  return {S:s*2*Math.PI/N, circulating:allPos};
}

function ebkLevel(n,L,c,N){
  const target=2*Math.PI*(n+0.5), cs=c.slice().sort((a,b)=>a-b);
  let lo=0.5*cs[0]*L*L*0.999, hi=0.5*cs[2]*L*L*1.001;
  for(let it=0;it<160;it++){ const mid=0.5*(lo+hi);
    if(ebkAction(mid,L,cs,N).S<target) lo=mid; else hi=mid; }
  return 0.5*(lo+hi);
}

function ebkCompare(j,bp,bm,nMax,N){
  const c=bixBetas(bp,bm).map(b=>Math.exp(-2*b)).sort((a,b)=>a-b);
  const L=j+0.5, ex=specEig(pcMuBlock(j,bp,bm)), rows=[];
  for(let n=0;n<=nMax&&2*n+1<ex.length;n++){
    const e=ebkLevel(n,L,c,N), mean=0.5*(ex[2*n]+ex[2*n+1]), split=Math.abs(ex[2*n+1]-ex[2*n]);
    /* THE PAIRING IS NOT AUTOMATIC.  Levels 2n and 2n+1 form a tunnelling doublet only in
       a genuinely ASYMMETRIC top.  Let the two axes coincide — beta_- = 0 gives c1 = c2 —
       and the structure becomes a singlet at m = 0 followed by EXACT +/-m pairs, so the
       (2n, 2n+1) pairing lands across two different levels and the "splitting" it reports
       is a real gap, not a tunnelling split.  A pair is only a doublet if it is much
       closer together than it is to its neighbours, and that is tested rather than
       assumed: without this the instrument returns confident nonsense on every axially
       symmetric top. */
    const near=2*n+2<ex.length?Math.abs(ex[2*n+2]-ex[2*n+1]):Infinity;
    const below=2*n>0?Math.abs(ex[2*n]-ex[2*n-1]):Infinity;
    const isDoublet=split<0.2*Math.min(near,below);
    rows.push({n, ebk:e, doubletMean:mean, splitting:split,
      relativeError:Math.abs(e-mean)/Math.abs(mean),
      pairing:isDoublet?'tunnelling doublet'
        :'NOT a doublet — these two levels are not a symmetric/antisymmetric pair, so the mean is not the quantity EBK predicts. This happens whenever two axes coincide (beta_- = 0 gives c1 = c2), where the structure is a singlet followed by exact +/-m pairs',
      /* and beyond about j = 24 a genuine splitting falls under what double precision can
         resolve against a level of order 10^2 */
      splittingResolved:isDoublet&&split/Math.abs(mean)>1e-14});
  }
  return {c, L, levels:rows};
}

const PHI_R=(1+Math.sqrt(5))/2;

const edgeMu   =l=>2*l+1;

const edgeBr   =(l,q)=>(l*(l+1)<=q?1:0);

const edgeAPS  =(l,C)=>C/(l+1);

const edgeRdiag=(l,q,C)=>Math.pow(PHI_R,l)*edgeMu(l)*Math.exp(-edgeAPS(l,C))*edgeBr(l,q);

function edgeNaiveRoot(C){
  const f=N=>N*Math.log(PHI_R)-Math.log(N*N+C);
  let lo=1.5,hi=400; if(f(lo)*f(hi)>0) return NaN;
  for(let i=0;i<300;i++){ const m=(lo+hi)/2; (f(lo)*f(m)<=0?hi=m:lo=m); }
  return (lo+hi)/2;
}

const edgePval=z=>(z-1)*z*(z+1)*(z+2)*(z+3);

function edgeEtaAbs(x,y,K=200){ let re=-2*Math.PI*y/24;
  for(let n=1;n<=K;n++){ const r=Math.exp(-2*Math.PI*y*n), a=2*Math.PI*x*n;
    const zr=1-r*Math.cos(a), zi=-r*Math.sin(a);
    re+=0.5*Math.log(zr*zr+zi*zi); if(r<1e-40) break; }
  return Math.exp(re); }

const edgeKL=(x,y)=>Math.log(Math.sqrt(y)*Math.pow(edgeEtaAbs(x,y),2));

function edgeEisenstein(k,x,y,K=200){
  const c=k===2?-24:k===4?240:-504, p=k===2?1:k===4?3:5; let re=1;
  for(let n=1;n<=K;n++){ let sg=0; for(let d=1;d<=n;d++) if(n%d===0) sg+=Math.pow(d,p);
    const r=Math.exp(-2*Math.PI*y*n); re+=c*sg*r*Math.cos(2*Math.PI*x*n); if(r<1e-40) break; }
  return re; }

const EDGE_ZETA_PRIME_M1=-0.1654211437004509;

const EDGE_LNDET_UNIT=0.5-4*EDGE_ZETA_PRIME_M1;

const EDGE_ZETA0_SCALAR=-2/3;

const EDGE_SPECIES=[
  {name:'chi  massless scalar',     op:'-∇₀²',      sigma:0.5, rank:1, trE: 0, n0:1},
  {name:'phi^a tachyonic scalars',  op:'-∇₀² - 2',  sigma:1.0, rank:1, trE:-2, n0:3},
  {name:'A_mu tachyonic vector',    op:'-∇₁² - 1',  sigma:0.5, rank:2, trE:-2, n0:6},
];

const edgeA1=(r,trE)=>r/3-trE;

const edgeZeta0=sp=>edgeA1(sp.rank,sp.trE)-sp.n0;

function edgeZetaFromSpecies(vectorN0){
  return EDGE_SPECIES.reduce((z,sp)=>z+sp.sigma*(sp.name.startsWith('A_mu')
    ? edgeA1(sp.rank,sp.trE)-(vectorN0??sp.n0) : edgeZeta0(sp)),0);
}

const edgeKappaNeeded=(N,C)=>Math.log(PHI_R)-Math.log(N*N+C)/N;

const edgeZetaEff=(N,C)=>-edgeKappaNeeded(N,C)/(2*Math.log(PHI_R));

function edgeRootWith(kappa,C){
  const f=N=>N*(Math.log(PHI_R)-kappa)-Math.log(N*N+C);
  if(Math.log(PHI_R)-kappa<=0) return null;                   /* no positive root at all */
  let lo=1.5,hi=1e5; if(f(lo)*f(hi)>0) return null;
  for(let i=0;i<400;i++){ const m=(lo+hi)/2; (f(lo)*f(m)<=0?hi=m:lo=m); }
  return (lo+hi)/2; }

const FIB_PHI=(1+Math.sqrt(5))/2;

const FIB_D=Math.sqrt(1+FIB_PHI*FIB_PHI);

const fibC=(re,im=0)=>({re,im});

const fibMul=(a,b)=>fibC(a.re*b.re-a.im*b.im,a.re*b.im+a.im*b.re);

const fibAdd=(a,b)=>fibC(a.re+b.re,a.im+b.im);

const fibExp=t=>fibC(Math.cos(t),Math.sin(t));

const fibMM=(A,B)=>A.map((r,i)=>B[0].map((_,j)=>r.reduce((s,_,k)=>fibAdd(s,fibMul(A[i][k],B[k][j])),fibC(0))));

const FIB_F=[[fibC(1/FIB_PHI),fibC(1/Math.sqrt(FIB_PHI))],
             [fibC(1/Math.sqrt(FIB_PHI)),fibC(-1/FIB_PHI)]];

const FIB_R1=fibExp(4*Math.PI/5), FIB_RT=fibExp(-3*Math.PI/5);

const FIB_S1=[[FIB_R1,fibC(0)],[fibC(0),FIB_RT]];

const FIB_S2=fibMM(fibMM(FIB_F,FIB_S1),FIB_F);

function fibFusion(n){ let a=1,b=0;
  for(let k=1;k<n;k++){ const na=a+b; b=a; a=na; }
  return {toTau:a, toVac:b, total:a+b}; }

function fibBraid(word){
  let M=[[fibC(1),fibC(0)],[fibC(0),fibC(1)]];
  for(const ch of String(word)){
    if(ch==='1') M=fibMM(M,FIB_S1);
    else if(ch==='2') M=fibMM(M,FIB_S2);
    else if(ch==='a') M=fibMM(M,[[fibC(FIB_R1.re,-FIB_R1.im),fibC(0)],[fibC(0),fibC(FIB_RT.re,-FIB_RT.im)]]);
  }
  return M; }

export {
  BIX_A, BIX_B, BIX_B2, BIX_C, BIX_C2, BIX_LY_CUT, BIX_LY_W0, CAP_BG2, CAP_D_H0, CAP_D_OMEGA, CAP_GATES, CAP_H0, CAP_LAM_OBS, CAP_LAM_SIG, CAP_LP, CAP_NU, CAP_N_PHI, CAP_OMEGA_L, CAP_PHI, CAP_Q_STAR, CAP_U_STAR, CAP_XI, EDGE_LNDET_UNIT, EDGE_SPECIES, EDGE_ZETA0_SCALAR, EDGE_ZETA_PRIME_M1, FBS, FIB_D, FIB_F, FIB_FR, FIB_N3, FIB_PHI, FIB_R1, FIB_RT, FIB_S1, FIB_S2, GLY_M, LN_PHI, LOG10_PHI, LY_M, PC_H, PHI, PHI_R, S3, ZPF, ZP_TH_BUDGET, bixBetas, bixClassify, bixD2V, bixDV, bixExtFlow, bixFlow, bixHtau, bixIntegrate, bixJAC, bixJacobian, bixLapse, bixLyapExp, bixLyapunov, bixSeed, bixShear, bixStep, bixV, capBg2, capGamma, capGammaD, capGateBudget, capLambda, capNphi, capSigma, ebkAction, ebkCompare, ebkLevel, edgeA1, edgeAPS, edgeBr, edgeEisenstein, edgeEtaAbs, edgeKL, edgeKappaNeeded, edgeMu, edgeNaiveRoot, edgePval, edgeRdiag, edgeRootWith, edgeZeta0, edgeZetaEff, edgeZetaFromSpecies, fibAdd, fibAxiomCache, fibAxioms, fibBraid, fibC, fibExp, fibFR, fibFsym, fibFusion, fibHexagon, fibMM, fibMonodromy, fibMul, fibPentagon, fibSMatrix, levelR, pcCreate, pcExtFlow, pcMu, pcMuBlock, specBlock, specC, specEig, specSpectrum, zpActionInvariant, zpBareEnergy, zpBose, zpCasimirAction, zpCasimirCompactness, zpCasimirDensity, zpCasimirEnergy, zpCompactness, zpEqualTemperature, zpHopfCharges, zpMeanModeEnergy, zpModeEnergy, zpModeTemperature, zpOmega, zpRung, zpShellEnergy, zpTemperatureOf, zpThermalScalarFactor, zpThermalTermsNeeded
};
